### ISSUE TITLE
NMOS и PMOS тразнисторы

### ISSUE THREAD

**Issue by nefedovms** [MPSU/APS#100]
На странице How FPGA works.md ошибка в рисунке 5. Там перепутано значение gate при котором открывается NMOS и PMOS тразнисторы. 
![image](https://github.com/user-attachments/assets/6a84fea4-30b8-4d73-b1b0-1285df7ec94a)

Далее абзац про И-НЕ содержит ошибки:
Подача значения **1** на вход А или B "открывает" соответствующий **n-канальный транзистор (обозначен на рис. 6 синим цветом)**, и закрывает соответствующий (комплементарный) **p-канальный транзистор (обозначен красным цветом)**.

**Comment by HepoH3** [comment]
Большое спасибо за сообщение!
