### ISSUE TITLE
6 лабораторная

### ISSUE THREAD

**Issue by Korben-detka** [MPSU/APS#95]
Не проходит тест 6 лабы, мне кажется, что проблема в TB, а не у меня.
Данные не по адресам сравниваются.
Пример: видно что по нулевому адресу лежит записанное число (интересно, что запись происходит до начала тб), однако тб сравнивает его с данными, идущими в ячейку 2, 3...
![image](https://github.com/user-attachments/assets/d7885914-d22b-4caa-a01a-d36edac289fa)
![image](https://github.com/user-attachments/assets/7a9fbbb9-a0d4-4224-a963-eb7ce10420ba)

**Comment by HepoH3** [comment]
Входной адрес записи и номер ячейки в памяти — понятия связанные, но не одинаковые. На протяжении первых четырех тактов тб ожидает что будет производиться запись в нулевую ячейку памяти (с которой ассоциированы адреса 0, 1, 2, 3, см. "побайтовая адресация"), однако запись ведется в нулевую, первую, вторую и третью ячейки, что и приводит к ошибке. Судя по синему цвету шины адреса видно, что какие-то биты там не подключены, возможно было неправильно реализовано преобразование входного адреса записи в адрес конкретной ячейки памяти.

**Comment by Korben-detka** [comment]
Да, просто надо было 2 бита младшие адреса не брать, а синим я просто выделил )))
